# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Codemageddon
tagline:             'musings on software engineering, distributed systems, technobabble'
description:         'a <a href="http://jekyllrb.com" target="_blank">placeholder</a>'
url:                 http://jakeokt.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Jake Oktaw
  url:               https://twitter.com/jakeokt

# Custom vars
version:             1.0.0

kramdown:
  input: GFM
